language: cpp

sudo: required

cache:
  directories:
    - i686-elf

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pmake
  - sudo ln -s /usr/bin/pmake /usr/bin/bmake
  - wget -N 'https://onedrive.live.com/download?cid=C3ABD0BC4C0161ED&resid=C3ABD0BC4C0161ED%2115450&authkey=AEvNf51Lv0uc9aU' -O i686-elf.tar.xz
  - tar xJf i686-elf.tar.xz

script:
  - make autobuild
  - make test

notifications:
  irc:
    channels:
      - "irc.freenode.net#metrika"
    template:
      - "%{repository}#%{build_number} (%{author}: %{commit_message}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
