language: cpp

sudo: required

cache:
  directories:
    - obj.i686

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq -y
  - sudo apt-get install -y pmake
  - sudo ln -s /usr/bin/pmake /usr/bin/bmake
  - sudo apt-get install -y gcc-5 g++-5
  - wget 'https://onedrive.live.com/download?cid=C3ABD0BC4C0161ED&resid=C3ABD0BC4C0161ED%2115450&authkey=AEvNf51Lv0uc9aU' -O i686-elf.tar.xz
  - tar xJf i686-elf.tar.xz
  - export PATH=${PATH}:$PWD/i686-elf/bin
  - export CXX=g++-5
  - export CC=gcc-5

script:
  - make autobuild
  - make test

notifications:
  irc:
    channels:
      - "irc.freenode.net#metrika"
    template:
      - "%{repository}#%{build_number} (%{author}: %{commit_message}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
